---
- name: Copy sqid python support scripts
  copy:
    src: "{{ scripts_path }}"
    dest: "{{ scripts_dest }}"

- name: Register sqid-update-statistics cron job
  cron:
    name: sqid-update-statistics
    minute: "12"
    job: "/usr/bin/jsub -mem 2g -N sqid-update-statistics -once python3 {{ scripts_dest }}/python/update-statistics.py > /dev/null 2>&1 || true"
    user: tools.sqid
    state: present
  tags: [cron]

- name: Register sqid-check-dump cron job
  cron:
    name: sqid-check-dump
    minute: "37"
    job: "/usr/bin/jsub -mem 2g -N sqid-check-dump -once python3 {{ scripts_dest }}/python/update-statistics.py --only=check-dump > /dev/null 2>&1 || true"
    user: tools.sqid
    state: present
  tags: [cron]
